name: labs-calling-deploymnet-workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: vktestorg/test_worfklow/.github/workflows/main.yml@main
    permissions:
      issues: write
    with:
      username: vikramk20
    secrets: inherit
